import { testEnv } from '../environment';

describe('React application', () => {
  const { mainApp } = testEnv.beforeAndAfter();

  it('should display title', async () => {
    await page.goto(mainApp.getUrl('/'));

    await page.waitForSelector('h2');
    expect(await page.$eval('h2', (e) => e.textContent)).toEqual(
      'This project was generated by Yoshi!',
    );
  });
});
